name: Deploy Docker Hub

on:
  push:
    tags:
      - v*
      - "!v*-rc"

jobs:
  deploy:
    name: Deploying to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Preset Image Name
        run: echo "IMAGE_URL=$(echo secondculs/coolify-env-fetcher:${GITHUB_REF#refs/*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build base layer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: build
          push: false
          cache-from: |
            type=gha,scope=build
          cache-to: |
            type=gha,scope=build,mode=max
      - name: Build final layer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: app
          cache-from: |
            type=gha,scope=build
            type=gha,scope=app
          cache-to: |
            type=gha,scope=app,mode=max
          push: true
          tags: ${{ env.IMAGE_URL }}
